### ISSUE TITLE
Missing texture: silver ring

### ISSUE THREAD

**Issue by avaer** [webaverse/loot-assets#1]
```
three.module.js:41798 GET https://webaverse.github.io/loot-assets/ring/Silver_Ring/Ring_emissive.png 404
react_devtools_backend.js:4049 THREE.GLTFLoader: Couldn't load texture Ring_emissive.png
```

**Comment by Vianvolaeus** [comment]
There wasn't an emissive texture made for this, so I'm not sure why it's even referencing it as a texture. 
![image](https://user-images.githubusercontent.com/80061436/134003336-1b528c6c-54e3-41d4-b5b1-a565dadb6ba4.png)

**Comment by madjin** [comment]
tested and not getting any such error on this anymore, time to close this issue?
