### ISSUE TITLE
Model scale: ring extremely overscaled

### ISSUE THREAD

**Issue by avaer** [webaverse/loot-assets#3]
![image](https://user-images.githubusercontent.com/6926057/133953796-2ca62439-3ace-4693-9348-08c6899381cd.png)

**Comment by Vianvolaeus** [comment]
Appears that somewhere either the GLB output from SP and the import into Blender results in a scale change of 1000x. Tested with a few other exp/imports and it's a recurring thing.

Scaling down the ring to reverse that corrects the scale. 
![image](https://user-images.githubusercontent.com/80061436/134004449-788eec8d-a34b-4864-b41c-23ff6b160624.png)
