### ISSUE TITLE
Token design

### ISSUE THREAD

**Issue by madjin** [webaverse/loot-assets#8]
1. Bundle onto a single avatar / knight stand GLB

![](https://i.imgur.com/y7RcJOL.png)

It'd be 1 GLB with each object as a separate node in blender minted as a NFT so previews can be 3D that can be rotated, zoomed in, etc

Perhaps there can be a default reference mannequin / avatar in place (VRoid base model best IMO)
Could add rarity skins for fun, adding in an original ingredient to the mix for this project

2. Unbundle and mint separately (per unbundled loot NFT)

Could use loot bag as token access to mint 8 ERC-1155 NFTs
Maybe could burn token of mloot instead of access
I think community might support this since there's an abundance of mloot supply 

- https://twitter.com/dhof/status/1434180216444923923 announcement
- https://opensea.io/collection/more-loot

alternatively can use lootloose and mint individual items https://twitter.com/dhof/status/1434180216444923923

**Comment by ahadshams** [comment]
in favour of the following in this order (highest to lowest)
1. mint individual items
2. Unbundle and mint separately

**Comment by avaer** [comment]
What does this issue have to do with webaverse?

**Comment by madjin** [comment]
moved here https://github.com/M3-org/m3taloot/issues/3
